# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: package

on:
  push:
    branches: [ main, develop ]
    paths:
    - 'src/**'
    - 'tests/**'
    - '.github/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'src/**'
    - 'tests/**'
    - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov pytest-asyncio rich
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Running tests
      run: |
        pytest -s tests --cov=./ --cov-config=.coveragerc --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
